#! /bin/sh
### BEGIN INIT INFO
# Provides: gige camera grab
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Grab
# Description: This file starts and stops gige camera capturing
#
### END INIT INFO

export GRAB_USER=jondoe
export GRAB_PATH=/tmp/
export GRAB_EXPOSURE=800
export GRAB_HEIGHT=32

export GRAB_PID=/var/run/grab.pid

# some pylon stuff
export PYLON_ROOT=/opt/pylon4
export GENICAM_ROOT_V2_3=$PYLON_ROOT/genicam
export GENICAM_CACHE_v2_3=${HOME}/genicam_xml_cache
gclibdir=$GENICAM_ROOT_V2_3/bin/Linux64_x64
pylonlibdir=$PYLON_ROOT/lib64
export LD_LIBRARY_PATH=$pylonlibdir:$gclibdir:$gclibdir/GenApi/Generic:$LD_LIBRARY_PATH



case "$1" in
 start)
   start-stop-daemon --start --quiet --chuid $GRAB_USER    \
    --make-pidfile --pidfile $GRAB_PID --background       \
    --startas /bin/bash -- -c "exec grab > /var/log/grab.log 2>&1"
   ;;
 stop)
   start-stop-daemon --stop --pidfile $GRAB_PID
   ;;
 restart)
   start-stop-daemon --stop --pidfile $GRAB_PID
   sleep 1
   start-stop-daemon --start --quiet --chuid $GRAB_USER    \
    --make-pidfile --pidfile $GRAB_PID --background       \
    --startas /bin/bash -- -c "exec grab > /var/log/grab.log 2>&1"
   ;;
 *)
   echo "Usage: grab-service {start|stop|restart}" >&2
   exit 3
   ;;
esac

# HINTS
# place this file in /etc/init.d
#
# make it executeable
# > sudo chmod a+x grab-service
# register as init script
# sudo update-rc.d grab-service defaults
